### ISSUE TITLE
how to get this dataset?

### ISSUE THREAD

**Issue by 616259098** [lseventeen/DIAS#3]
nice work,but how to geit this dataset

**Comment by 616259098** [comment]
nice job

**Comment by lseventeen** [comment]
Thank you for your interest. Once our work is accepted, we will make the data public.

**Comment by XinAloha** [comment]
@lseventeen Hello, this work is very meaningful. Can we access the data now?

**Comment by lseventeen** [comment]
Thank you for your interest in our work. [DIAS](https://zenodo.org/records/11402259) is publicly available!

If you have any questions or need further information, please feel free to contact us.
